version: '3'
services:
    app:
      build: .
      container_name: flask_app
      environment:
        - DB_HOST=mysql
        - DB_USER=root
        - DB_PASSWORD=rootpassword
        - DB_NAME=arac_kiralama
      depends_on:
        - mysql
      networks:
        - app-network
      ports:
        - "8000:8000"

    mysql:
      image: mysql:5.7
      container_name: mysql_container
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: arac_kiralama
      networks:
        - app-network
      ports:
        - "3306:3306"

    nginx:
      image: nginx:latest
      container_name: nginx_reverse_proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
       - "80:80"
      depends_on:
        - app
      networks:
        - app-network

networks:
    app-network:
      driver: bridge